module.exports = {
    varchar: 'String',
    char: 'String',
    tinytext: 'String',
    text: 'String',
    mediumtext: 'String',
    longtext: 'String',
    int: 'Int',
    tinyint: 'Int',
    smallint: 'Int',
    mediumint: 'Int',
    bigint: 'Int',
    float: 'Float',
    double: 'Float',
    real: 'Float',
    decimal: 'Float',
    date: 'String',
    time: 'String',
    datetime: 'String',
    timestamp: 'String',
    year: 'String',
};